# Generated by Django 4.2.4 on 2023-08-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ssn', models.CharField(max_length=11, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('loan_amount', models.IntegerField()),
                ('equity_amount', models.IntegerField()),
                ('salary_amount', models.IntegerField()),
            ],
        ),
    ]
